scrape_configs:
  - job_name: 'PetClinicMetrics'
    metrics_path: '/petclinic/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:9966']
        labels:
          application: 'Petclinic Spring Boot Application'
